version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build: .
    container_name: semantic-search-app
    env_file:
      - .env
    environment:
      QDRANT_URL: http://qdrant:6333
      QDRANT_API_KEY: ""
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - .:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  qdrant_data: 